### ISSUE TITLE
Color indication for tracking and advertising domains

### ISSUE THREAD

**Issue by illusionist003** [AdguardTeam/AdguardForiOS#1584]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

The DNS request page doesn't show the color code is did in the previous versions as Red being blocked, white being non responsive or non tracking, and  yellow being a tracker/ad.

### Proposed Solution

Bring back the yellow to show what DNS request are trackers so it will make it easier to eliminate ads 
![632F8F21-58F7-4AB9-AD6F-8F906F95B61B](https://user-images.githubusercontent.com/67205869/85210892-e0780780-b311-11ea-93e1-ac39a17989cb.jpeg)

### Alternatives Considered

Possibly removing the 3 main tabs and changing it to 2 tabs or back to the original one page making the GUI much more user friendly and bring back the yellow highlighted DNS requests that are trackers

**Comment by bigdargon** [comment]
@illusionist003  Dup #1579

**Comment by lancelot-moon** [comment]
@ameshkov See, users like the previous idea (traffic light’s colors) for DNS log.)))

**Comment by ameshkov** [comment]
I wouldn't risk returning the yellow color as it was, App Store reviewers may consider that AG blocks something by default and I am not ready going through the review&appeal ordeal again.

Most likely we'll add a small colored circle indicating the request type.
