### ISSUE TITLE
Fix the most popular crashes in v4.3.2

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1939]
Some of them are caused by external issues we cannot influence, but it does not mean we shouldn't take a closer look. I'll try to update this tomorrow in the morning and check which of them can be fixed or mitigated if possible.

* [x] `AdGuardSdkDependencies: partial apply for thunk for @callee_guaranteed () -> (@unowned Bool, @error @owned Error) + 24`
* [x] `UIFoundation: UINibDecoderDecodeObjectForValue + 780` in "AdGuardTodayExtension" -- this might be causing #1510  
* [x] `Adguard: MigrationService.minorAndPatchMigration() + 984`
* [x] `Adguard: implicit closure #2 in implicit closure #1 in RulesParser.parse(raw:) + 16`
* [x] `DnsAdGuardSDK: closure #1 in closure #1 in ActivityStatistics.getCompressedRecords() + 8`
* [x] `Adguard: SDKMigrationServiceHelper.migrate() + 40`
* [x] `AdGuardSdkDependencies: Statement.bind(_:) + 12`
